import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { isValidJsVariable } from '@technobuddha/library';
import chalk from 'chalk';
import sane from 'sane';

import { type Logger } from '../common/index.ts';

import parser from './parser.ts';

export type CMTDOptions = {
  rootDirectoryPath?: string;
  inputDirectoryName?: string;
  outputDirectoryName?: string;
  globPattern?: string;
  dropExtensions?: boolean;
  camelCase?: boolean;
  logger?: Logger;
  config?: unknown;
};

export class CMTD {
  private readonly rootDirectoryPath: string;
  private readonly inputDirectoryName: string;
  private readonly outputDirectoryName: string;
  private readonly globPattern: string;
  private readonly dropExtensions: boolean;
  private readonly camelCase: boolean;
  private readonly logger: Logger;
  private readonly config: unknown;

  public constructor({
    rootDirectoryPath,
    inputDirectoryName,
    outputDirectoryName,
    globPattern,
    dropExtensions,
    camelCase,
    logger,
    config,
  }: CMTDOptions) {
    this.rootDirectoryPath = rootDirectoryPath ?? process.cwd();
    this.inputDirectoryName = inputDirectoryName ?? '.';
    this.outputDirectoryName = outputDirectoryName ?? this.inputDirectoryName;
    this.globPattern = globPattern ?? '**.*.css';
    this.dropExtensions = dropExtensions ?? false;
    this.camelCase = camelCase ?? false;
    this.logger = logger ?? console;
    this.config = config ?? undefined;
  }

  private async generateTypes(filePath: string): Promise<void> {
    return new Promise<void>((resolve, reject) => {
      parser(filePath, this.config)
        .then((tokens) => {
          const fileName =
            path.isAbsolute(filePath) ? path.relative(this.inputDirectoryName, filePath) : filePath;
          const outputDirectoryPath = path.resolve(
            this.rootDirectoryPath,
            this.outputDirectoryName,
          );
          const outputFileBase = this.dropExtensions ? CMTD.removeExtension(fileName) : fileName;
          const outputFilePath = path.join(outputDirectoryPath, `${outputFileBase}.d.ts`);

          const declarations: string[] = [];
          for (const token of Array.from(tokens.keys()).sort()) {
            let key = token;
            let valid = isValidJsVariable(key);

            if (this.camelCase) {
              const camelKey = CMTD.toCamelCase(key);

              if (camelKey !== key) {
                declarations.push(`'${key}'`);
                key = camelKey;
                valid = isValidJsVariable(key);
              }
            }

            if (valid) {
              declarations.push(`'${key}'`);
            } else {
              declarations.push(`'${key}'`);
              this.logger.info(`{CMTD} ${chalk.yellow(`${fileName}: Invalid ${key}`)}`);
            }
          }

          if (!CMTD.exists(outputDirectoryPath)) {
            fs.mkdirSync(outputDirectoryPath, { recursive: true });
          }

          let fileContent = [
            '/*',
            ' *  This file is automatically generated by css-module-type-definitions',
            ' */',
            '',
          ];

          fileContent =
            declarations.length > 0 ?
              fileContent.concat([
                `export type Keys = ${declarations.join(` | `)};`,
                'export type css = { [key in Keys]: string };',
              ])
            : fileContent.concat(['export type Keys = never;', 'export type css = never;']);

          fileContent = fileContent.concat(['', 'declare const css: css;', 'export default css;']);

          let existing = '';
          const replacement: string = fileContent.join(os.EOL) + os.EOL;
          if (fs.existsSync(outputFilePath)) {
            existing = fs.readFileSync(outputFilePath, 'utf-8');
          }

          if (existing === replacement) {
            resolve();
          } else {
            void fs.promises.writeFile(outputFilePath, replacement, 'utf-8').then(() => {
              this.logger.info(`{CMTD} ${chalk.green('Types Generated for')} ${fileName}`);
              resolve();
            });
          }
        })
        .catch((x) => {
          this.logger.error(x);
          reject(x as Error);
        });
    });
  }

  public async scan(): Promise<void> {
    for await (const file of fs.promises.glob(
      path.join(path.resolve(this.rootDirectoryPath, this.inputDirectoryName), this.globPattern),
    )) {
      await this.generateTypes(file);
    }
  }

  public watch(): void {
    const DELAY = 10; // Number of milliseconds to delay for file to finish writing
    const target = path.resolve(this.rootDirectoryPath, this.inputDirectoryName);

    this.logger.info(
      `{CMTD} ${chalk.blue('Watching')} ${this.inputDirectoryName} ${this.globPattern}`,
    );

    const watcher = sane(target, { glob: this.globPattern });

    watcher.on('add', (f) => void this.generateTypes(path.join(target, f)));
    watcher.on('change', (f) =>
      setTimeout(() => void this.generateTypes(path.join(target, f)), DELAY),
    );
  }

  private static removeExtension(filePath: string): string {
    const ext = path.extname(filePath);
    return filePath.replace(new RegExp(`${ext}$`, 'v'), '');
  }

  private static exists(pathname: string): boolean {
    try {
      fs.statSync(pathname);
      return true;
    } catch {
      return false;
    }
  }

  private static toCamelCase(str: string): string {
    return str.replaceAll(/-+(\w)/gv, (_match, firstLetter) => firstLetter.toUpperCase());
  }
}

export { CMTDWebpackPlugin } from './plugin.ts';
export default CMTD;
