import fs from 'node:fs/promises';
import os from 'node:os';

import { camelCase } from '@technobuddha/library';
import { format, resolveConfig } from 'prettier';

import { type CMTDOptions } from './cmtd-options.ts';
import { extractClassnames } from './extract-classnames.ts';
import { isValidToken } from './is-valid-token.ts';

/**
 * Converts dashes to camelCase by capitalizing the letter following each dash sequence.
 *
 * This is a simpler alternative to full camelCase conversion that only handles
 * dash-separated words, similar to CSS property name conversion (e.g., `background-color` → `backgroundColor`).
 *
 * @param text - The text to convert
 * @returns The text with dashes removed and following letters capitalized
 *
 * @example
 * ```ts
 * dashesCamelCase('my-class-name');     // 'myClassName'
 * dashesCamelCase('button--primary');   // 'buttonPrimary'
 * dashesCamelCase('nav-bar');           // 'navBar'
 * ```
 *
 * @internal
 */
function dashesCamelCase(text: string): string {
  return text.replaceAll(/-+(\w)/gv, (_, firstLetter) => firstLetter.toUpperCase());
}

/**
 * Generates a TypeScript declaration file (`.d.ts`) for a CSS module file.
 *
 * This function extracts class names from the CSS module, converts them according to
 * the specified naming convention, and generates a strongly-typed TypeScript declaration
 * file that includes:
 * - A `Classes` type union of all class name strings
 * - A `Locals` type mapping class names to strings
 * - Named exports for each valid JavaScript identifier
 * - A default export of the Locals object
 *
 * The generated file is formatted using Prettier and only written if the content has changed.
 *
 * @param file - Absolute path to the CSS module file
 * @param options - Configuration options for type generation
 *
 * @example
 * ```ts
 * // Generate types for a CSS module
 * await generateDeclarationFile('./styles.module.css', {
 *   localsConvention: 'camelCase'
 * });
 *
 * // Generated file: styles.module.css.d.ts
 * // export type Classes = "myClass" | "anotherClass";
 * // export type Locals = { readonly [c in Classes]: string };
 * // export declare const myClass: string;
 * // export declare const anotherClass: string;
 * // declare const __default: Locals;
 * // export default __default;
 * ```
 *
 * @group Core
 * @category Type Generation
 */
export async function generateDeclarationFile(
  file: string,
  options: CMTDOptions = {},
): Promise<void> {
  const { localsConvention = 'camelCase' } = options;

  return extractClassnames(file).then(async (classNames): Promise<void> => {
    if (classNames.size > 0) {
      const outputPath = `${file}.d.ts`;
      const classes: string[] = [];
      const exports: string[] = [];

      for (const className of classNames) {
        const localClassName =
          localsConvention === 'camelCase' || localsConvention === 'camelCaseOnly' ?
            camelCase(className)
          : localsConvention === 'dashes' || localsConvention === 'dashesOnly' ?
            dashesCamelCase(className)
          : localsConvention(className, camelCase(className), file);

        if (
          className !== localClassName &&
          localsConvention !== 'camelCaseOnly' &&
          localsConvention !== 'dashesOnly'
        ) {
          classes.push(`"${className}"`);
        }

        classes.push(`"${localClassName}"`);

        if (isValidToken(localClassName)) {
          exports.push(`export declare const ${localClassName}: string;`);
        }
      }

      const output: string[] = [
        '/* eslint-disable @typescript-eslint/naming-convention */',
        '/*',
        ' *  This file is automatically generated by css-module-type-definitions',
        ' */',
        '',
        `export type Classes = ${classes.join(` | `)};`,
        'export type Locals = { readonly [c in Classes]: string };',
        '',
        ...exports,
        '',
        'declare const __default: Locals;',
        'export default __default;',
      ];

      const config = await resolveConfig(outputPath);
      const formatted = await format(output.join(os.EOL) + os.EOL, {
        ...config,
        parser: 'typescript',
      });

      let existing: string;
      try {
        existing = await fs.readFile(outputPath, 'utf-8');
      } catch {
        existing = '';
      }
      if (existing === formatted) {
        return;
      }

      // eslint-disable-next-line no-console
      console.log('{CMTD} Types Generated for', file);
      await fs.writeFile(outputPath, formatted, 'utf-8');
    }
    return undefined;
  });
}
